version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  version: 2.1
  build-push:
    jobs:
      - build_and_push_image:
          context:
            - AWS_CREDENTIALS

jobs:
  build_and_push_image:
    description: Build prometheus-ecs-discovery image and push it to AWS ECR
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - run:
          name: Build and push to AWS ECR
          command: |
            export IMAGE_TAG=1.0.${CIRCLE_BUILD_NUM}
            docker build --tag ${AWS_ECR_ACCOUNT}/metrifico:1.0.${CIRCLE_BUILD_NUM} .
            # export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            # export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            # export AWS_REGION=${AWS_REGION}
            # export AWS_ECR_REGISTRY=395499912268.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
            aws ecr get-login-password | docker login --username AWS --password-stdin https://${AWS_ECR_ACCOUNT}
            docker push ${AWS_ECR_REGISTRY}/prometheus-ecr-discovery
            # export MANIFEST=$(aws ecr batch-get-image --repository-name metrifico --image-ids imageTag=1.0.${CIRCLE_BUILD_NUM} --query 'images[].imageManifest' --output text)
            # aws ecr put-image --repository-name metrifico --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"
