version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  version: 2.1
  build-push:
    jobs:
      - build_and_push_image:
          context:
            - AWS_CREDENTIALS

jobs:
  build_and_push_image:
    description: Build prometheus-ecs-discovery image and push it to ECR
    machine:
      image: 'ubuntu-2004:current'
    resource_class: medium
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          region: AWS_DEFAULT_REGION
          repo: prometheus-ecs-discovery
          skip-when-tags-exist: false
          tag: 'v1.0.${CIRCLE_BUILD_NUM},latest'
